version: '3.8'

services:
  go-api:
    build:
      context: ./apis/go
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    container_name: go-calculator

  js-api:
    build:
      context: ./apis/js
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: js-calculator

  python-api:
    build:
      context: ./apis/python
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: python-calculator

  rust-api:
    build:
      context: ./apis/rust
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: rust-api
