version: '3.8'

services:

  go-api:
    build:
      context: ./go-api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
